import type { Node } from '@antv/x6'
import { rectPorts } from '../ports/ports'

export const flowchartDatabase: Node.Config = {
  inherit: 'rect',
  width: 160,
  height: 90,
  markup: [
    { tagName: 'rect', selector: 'body' },
    { tagName: 'ellipse', selector: 'bottomCap' },
    { tagName: 'rect', selector: 'bodyFill' },
    { tagName: 'line', selector: 'leftLine' },
    { tagName: 'line', selector: 'rightLine' },
    { tagName: 'ellipse', selector: 'topCap' },
    { tagName: 'text', selector: 'label' },
  ],
  attrs: {
    body: {
      refWidth: 1,
      refHeight: 1,
      fill: 'transparent',
      stroke: 'none',
    },
    bottomCap: {
      refCx: 0.5,
      refCy: 0.833333,
      refRx: 0.4375,
      refRy: 0.111111,
      fill: 'none',
      stroke: '#334155',
      strokeWidth: 2,
    },
    bodyFill: {
      refX: 0,
      refY: 0.166667,
      refWidth: 1,
      refHeight: 0.666667,
      fill: '#f8fafc',
      stroke: 'none',
    },
    leftLine: {
      x1: '0%',
      y1: '27.78%',
      x2: '0%',
      y2: '72.22%',
      stroke: '#334155',
      strokeWidth: 2,
    },
    rightLine: {
      x1: '100%',
      y1: '27.78%',
      x2: '100%',
      y2: '72.22%',
      stroke: '#334155',
      strokeWidth: 2,
    },
    topCap: {
      refCx: 0.5,
      refCy: 0.166667,
      refRx: 0.4375,
      refRy: 0.111111,
      fill: '#f8fafc',
      stroke: '#334155',
      strokeWidth: 2,
    },
    label: {
      fill: '#334155',
      fontSize: 14,
      refX: 0.5,
      refY: 0.55,
      textAnchor: 'middle',
      textVerticalAnchor: 'middle',
    },
  },
  ports: rectPorts({ stroke: '#334155' }),
}
