export { basicRect } from './rect'
export { basicRoundedRect } from './roundedRect'
export { basicCircle } from './circle'
export { basicDiamond } from './diamond'
export { basicTriangle } from './triangle'
export { basicParallelogram } from './parallelogram'
export { basicTrapezoid } from './trapezoid'
export { basicHexagon } from './hexagon'
export { basicCylinder } from './cylinder'
export { basicPentagon } from './pentagon'
export { basicOctagon } from './octagon'
export { basicStar } from './star'
export { basicCross } from './cross'
export { basicCloud } from './cloud'
export { basicDocument } from './document'
export { basicTable } from './table'
export { basicText, basicImage, basicSvg } from './text'
